@BloggingPlatformAPI_HostAddress = http://localhost:5036

GET {{BloggingPlatformAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BloggingPlatformAPI_HostAddress}}/posts/
Accept: application/json

###
GET {{BloggingPlatformAPI_HostAddress}}/posts?title=2
Accept: application/json

###
GET {{BloggingPlatformAPI_HostAddress}}/posts/2
Accept: application/json

###


POST {{BloggingPlatformAPI_HostAddress}}/posts/
Content-Type: application/json

{
    "title": "title_new",
    "content": "content_new",
    "category": "category_new",
    "tags": ["new1", "new2"]
}

###

PUT {{BloggingPlatformAPI_HostAddress}}/posts/2
Content-Type: application/json

{
    "id": 2,
    "title": "title_new",
    "content": "content_new",
    "category": "category_new",
    "tags": ["new1", "new2"]
}

###

DELETE {{BloggingPlatformAPI_HostAddress}}/posts/2

###
